# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog @ 2b||!2b
email: admin@dietms.org
description: > # this means to ignore newlines until "baseurl:"
  A blog for 2b||!2b coding club. Built in jekyll static site generater.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://dietms.github.io/" # the base hostname & protocol for your site
facebook_username: diemscodingclub
github_username:  dietms

# Build settings
markdown: kramdown
